services:
  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - mongodb
      - redis
    env_file:
      - .env.production

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
    env_file:
      - .env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:4.4
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:6

volumes:
  postgres_data:
  mongodb_data:
